apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openprime-keycloak.fullname" . }}-realm-config
  labels:
    {{- include "openprime-keycloak.labels" . | nindent 4 }}
data:
  openprime-realm.json: |
    {
      "realm": "openprime",
      "enabled": true,
      "registrationAllowed": true,
      "resetPasswordAllowed": true,
      "rememberMe": true,
      "displayName": "OpenPrime",
      "sslRequired": "external",
      "accessTokenLifespan": 3600,
      "refreshTokenMaxReuse": 0,
      "ssoSessionIdleTimeout": 1800,
      "loginTheme": "openprime",
      "accountTheme": "openprime",
      "clients": [
        {
          "clientId": "openprime-app",
          "enabled": true,
          "publicClient": true,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "redirectUris": ["https://{{ .Values.openprime.frontendUrl }}/*"],
          "webOrigins": ["https://{{ .Values.openprime.frontendUrl }}"],
          "protocol": "openid-connect"
        }
      ],
      "users": []
    }
